### ISSUE TITLE
Requete Mise de côté car pas encore utilisé.

### ISSUE THREAD

**Issue by valentincharrier** [ocade-graciet-system/action-http-request#1]
Dans le fichier du workflows (en fin de fichier):
```
      - name: Envoyer une requête POST avec un corps JSON
        uses: ocade-graciet-system/action-http-request@v1
        with:
          url: 'https://builder.domaine.tld'
          method: 'POST'
          headers: '{"Content-Type": "application/json"}'
          body: '{"id": "ocade-pass", "password": "pass-ocade"}'

```
